repos:
- repo: https://github/psf/black
  rev: 21.5b2
  hooks:
  - id: black
- repo: https://github/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github/PyCQA/isort
  rev: 5.9.1
  hooks:
  - id: isort